### ISSUE TITLE
Renaming of Job description fields

### ISSUE THREAD

**Issue by DanilaOleynik** [PanDAWMS/pilot2#32]
Hi, 

We will may expire inconvenience in long term support in case we will use different names for job description fields in Pilot and in other components of PanDA. Minor changes like: converting to lower case, will work well, but changing of field name will work against us 

https://github.com/PanDAWMS/pilot2/blob/4977788ab717517f760f6713789d3c480ecc82b8/jobdescription.py#L258

**Comment by PalNilsson** [comment]
Hi, yes maybe some inconvenience some day, but on the other hand we can have field names that are actually better. I think there are several field names with really bad names and they never got changed because it is too complicated to do so. We can work internally in the pilot with better and more logical names. But actually Daniel designed the new component to support both the original names and new names only known by the pilot. We have had discussions about it in the past but I think it's better that we have the freedom to call things what we want. In the old pilot we do some renaming as well and it has never been a problem as far as I remember.
